@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "4.48.1";

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: "feature/.*"),
        customStages: [container: [enabled: false]],
        platforms: ['ol7', 'ol8', 'ol9'],
        yumOL7Repos: ['ol7_optional_latest', 'ol7_addons', 'ol7_developer_golang116'],
        yumOL8Repos:['ol8_appstream', 'ol8_codeready_builder'],
        yumOL9Repos:['ol9_appstream', 'ol9_codeready_builder']
)
