@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "4.47.1";

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        customStages: [container: [enabled: false]],
        platforms: ['ol8', 'ol9'],
        yumOL8Repos:['ol8_appstream', 'ol8_codeready_builder'],
        yumOL9Repos:['ol9_appstream', 'ol9_codeready_builder'],
        architectures: ['x86_64', 'aarch64'],
)
